### PR TITLE
Add golang lichess bot

### PR DESCRIPTION
**Pull request by dolegi**
Hello :wave:

I've created a chess bot interface for uci engines in golang. More details about it are available [here](https://github.com/dolegi/lichess-bot). The docs said add a PR.

Let me know what you think :)

### CODE REVIEW

**Comment by ddugovic** [comment]
I'd be glad to verify this with https://github.com/ddugovic/Stockfish although I've only once used golang and don't remember anything about it.

**Comment by dolegi** [comment]
@ddugovic You can run one of the pre-compiled binaries from [here](https://github.com/dolegi/lichess-bot/releases) with `./lichess-bot config.toml`
Or to run locally.
- Make sure your [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set
- Clone the repo
- Get the dependencies `go get -d .`
- `go run *.go config.toml`

**Comment by ddugovic** [comment]
Sorry, I'm attempting to test this on listage.ovh first however (even after regenerating my tokens and configuration) I'm having problems using that site with `lichess-bot.py`.

**Comment by ornicar** [comment]
Just use the prod website. I don't want to maintain oauth on stage.

**Comment by ornicar** [comment]
Can the bot handle the conversion of the account into a bot account? The python bot does that iirc.

**Comment by dolegi** [comment]
It can now :D, just added it, https://github.com/dolegi/lichess-bot#upgrade-to-bot-account

**Comment by ddugovic** [comment]
I have deployed https://lichess.org/@/GodelEscherBot using a fork of it https://github.com/ddugovic/lichess-bot-1/tree/variant

**Pull request merged**
