### PR TITLE
fix arena tournament example

### PR DESCRIPTION
**Pull request by schlawg**

### CODE REVIEW

**Comment by benediktwerner** [comment]
This is actually not so simple. The reason it's currently wrong is because the tournament object is referenced in multiple endpoints even though their responses aren't always the same. The "tournaments of the team" endpoint does return variants like it is currently documented.

Realistically, the proper solution would be to check the source code and properly document the responses for all the endpoints. I've started doing this on a train ride a little while ago but haven't really gotten around to finishing it.

But I guess you could at least make it two examples for now and ideally just make a real call to each endpoint and use that as the example for each.

**Comment by schlawg** [comment]
for compatibility i guess this should not be changed, but out of curiosity is there a reason for the difference?

**Comment by schlawg** [comment]
I just took a look at tournament/ApiJsonView and tournament/JsonView.  I think I will wait for your next train ride.

**Comment by schlawg** [comment]
hope this helps for now

**Pull request merged**
